### ISSUE TITLE
Update dependencies from the morley repository

### ISSUE THREAD

**Issue by gromakovsky** [serokell/tezos-globacap#34]
# Clarification and motivation

We would like to keep code more or less up-to-date with latest versions of its dependencies.

# Acceptance criteria

1. `morley` and `lorentz` are taken from Hackage, their versions are 1.5.0 and 0.5.0 respectively.
2. `morley-ledgers` is taken from https://gitlab.com/morley-framework/morley-ledgers (there is a MR that should be merged first).
3. Other packages from `morley` are taken from `0574c85b` (it corresponds to the aforementioned versions of `morley`).
4. Stackage resolver is updated to 16.5.
5. All `extra-deps` are filtered and don't contain any redundant entry (such as `tezos-bake-monitor-lib`).

**Comment by rvem** [comment]
3) I propose to use https://gitlab.com/morley-framework/morley/-/commit/697f606bc2564adda194063068c35737049c61f5 because the production version has very inconvenient [`callFrom`](https://gitlab.com/morley-framework/morley/-/blob/production/code/cleveland/src/Morley/Nettest/Caps.hs#L119) type because it uses untyped entrypoints.

**Comment by gromakovsky** [comment]
Ah, so types there are just wrong and broken. Okay, I suppose we can make 1.6.0 and 0.6.0 releases to address that. Will it solve this problem?

**Comment by rvem** [comment]
I think so

**Comment by rvem** [comment]
I'll try to use current morley master and see whether there are any additional difficulties

**Comment by gromakovsky** [comment]
Note that `morley-ledgers` may be somewhat incompatible with current master. We'll have to update it to use 1.6.0 first in that case.

**Comment by rvem** [comment]
It's indeed incompatible:(

**Comment by gromakovsky** [comment]
I've created https://gitlab.com/morley-framework/morley-ledgers/-/issues/2. Will do myself, unless you have already started doing something related.

**Comment by rvem** [comment]
Okay, will wait for it then
